/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.QuestaoDiscursiva;
import fachada.Fachada;
import fachada.IFachada;
import javax.swing.JOptionPane;


/**
 *
 * @author RAFAELSANTIAGO
 */
public class AlterarQuestaoDiscursiva extends javax.swing.JFrame {
     ListarQuestao lquestao;
    QuestaoDiscursiva questaoDiscursiva;
    IFachada fachada = Fachada.obterInstancia();
    long codigo;
    /**
     * Creates new form AlterarQuestaoDiscursiva
     */
    public AlterarQuestaoDiscursiva(ListarQuestao lquestao,QuestaoDiscursiva questaoDiscursiva) {
        initComponents();
        this.lquestao = lquestao;
        this.questaoDiscursiva = questaoDiscursiva;
        codigo= questaoDiscursiva.getId();
        textAreaTextoQuestao.setText(questaoDiscursiva.getTexto());
        textElaboradorQuestao.setText(questaoDiscursiva.getElaborador().getNome());
        textGeneroQuestao.setText(questaoDiscursiva.getGenero().getGenero());
        textReferenciaQuestao.setText(questaoDiscursiva.getReferencia());
        textAreaRespostaQuestao.setText(questaoDiscursiva.getResposta());
        textNumLinhas.setText(Integer.toString(questaoDiscursiva.getLinhas()));
        
    }

    private AlterarQuestaoDiscursiva() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textReferenciaQuestao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTextoQuestao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaRespostaQuestao = new javax.swing.JTextArea();
        ButtonCancelarQuestao = new javax.swing.JButton();
        ButtonAlterarQuestao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textGeneroQuestao = new javax.swing.JTextField();
        textElaboradorQuestao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNumLinhas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Referência");

        jLabel1.setText("Texto Questao");

        textReferenciaQuestao.setEnabled(false);

        textAreaTextoQuestao.setColumns(20);
        textAreaTextoQuestao.setRows(5);
        textAreaTextoQuestao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAreaTextoQuestao);

        textAreaRespostaQuestao.setColumns(20);
        textAreaRespostaQuestao.setRows(5);
        jScrollPane3.setViewportView(textAreaRespostaQuestao);

        ButtonCancelarQuestao.setText("Cancelar");
        ButtonCancelarQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarQuestaoActionPerformed(evt);
            }
        });

        ButtonAlterarQuestao.setText("Alterar");
        ButtonAlterarQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarQuestaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Genero");

        textGeneroQuestao.setEnabled(false);

        textElaboradorQuestao.setEnabled(false);

        jLabel5.setText("Num. Linhas");

        jLabel2.setText("Elaborador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(ButtonCancelarQuestao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAlterarQuestao)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNumLinhas, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textReferenciaQuestao))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textElaboradorQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(textGeneroQuestao))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textElaboradorQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textGeneroQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textReferenciaQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textNumLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAlterarQuestao)
                    .addComponent(ButtonCancelarQuestao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAlterarQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarQuestaoActionPerformed
        try {
            // TODO add your handling code here:
            questaoDiscursiva.setId(codigo);
            questaoDiscursiva.setLinhas(Integer.parseInt(textNumLinhas.getText()));
            questaoDiscursiva.setTexto(textAreaTextoQuestao.getText());
            questaoDiscursiva.setResposta(textAreaRespostaQuestao.getText());
            if (JOptionPane.showConfirmDialog(rootPane, "Você realmente quer Alterar esta questão?", "Alterar Questão", JOptionPane.YES_NO_OPTION) == 0) {
                fachada.atualizarQuestaoDiscursiva(questaoDiscursiva);
                JOptionPane.showMessageDialog(rootPane, "Questão Alterar com sucesso");
                lquestao.carregarListaQuestoesDiscursiva();
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_ButtonAlterarQuestaoActionPerformed

    private void ButtonCancelarQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarQuestaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarQuestaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarQuestaoDiscursiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarQuestaoDiscursiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarQuestaoDiscursiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarQuestaoDiscursiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarQuestaoDiscursiva().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlterarQuestao;
    private javax.swing.JButton ButtonCancelarQuestao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textAreaRespostaQuestao;
    private javax.swing.JTextArea textAreaTextoQuestao;
    private javax.swing.JTextField textElaboradorQuestao;
    private javax.swing.JTextField textGeneroQuestao;
    private javax.swing.JTextField textNumLinhas;
    private javax.swing.JTextField textReferenciaQuestao;
    // End of variables declaration//GEN-END:variables
}
