/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Elaborador;
import classes.Endereco;
import fachada.Fachada;
import fachada.IFachada;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RAFAELSANTIAGO
 */
public class AlterarElaborador extends javax.swing.JFrame {
      IFachada fachada = Fachada.obterInstancia();
      long cod;
      ListarElaborador le;
    /**
     * Creates new form AlterarElaborador
     */
    public AlterarElaborador(Elaborador elaborador,ListarElaborador le) {
        initComponents();
        this.le=le;
        cod= elaborador.getId();
        textNomeElaborador.setText(elaborador.getNome());
        textCPFElaborador.setText(elaborador.getCpf());
        textRGElaborador.setText(elaborador.getRg());
        textCelularElaborador.setText(elaborador.getCelular());
        textTelefoneElaborador.setText(elaborador.getTelefone());
        textDataNascElaborador.setText((elaborador.getData_nasc().get(5) + "/" + elaborador.getData_nasc().get(2) + "/" + elaborador.getData_nasc().get(1)));
        ComboFormacaoElaborador1.setSelectedItem(elaborador.getFormacao());
        textCidadeElaborador.setText(elaborador.getEndereco().getCidade());
        textBairroElaborador.setText(elaborador.getEndereco().getBairro());
        textCEPElaborador.setText(elaborador.getEndereco().getCep());
        comboUFElaborador.setSelectedItem(elaborador.getEndereco().getUf());
        textLogradouroElaborador.setText(elaborador.getEndereco().getLogradouro());
        textNumeroElaborador.setText(elaborador.getEndereco().getNumero());
        textComplementoElaborador.setText(elaborador.getEndereco().getComplemento());
    }

    private AlterarElaborador() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        textDataNascElaborador = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textComplementoElaborador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textNomeElaborador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNumeroElaborador = new javax.swing.JTextField();
        buttonCancelarElaborador = new javax.swing.JButton();
        buttonAtualizarElaborador = new javax.swing.JButton();
        textBairroElaborador = new javax.swing.JTextField();
        textLogradouroElaborador = new javax.swing.JTextField();
        textCPFElaborador = new javax.swing.JFormattedTextField();
        textTelefoneElaborador = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        textCidadeElaborador = new javax.swing.JTextField();
        textCEPElaborador = new javax.swing.JFormattedTextField();
        textRGElaborador = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textCelularElaborador = new javax.swing.JFormattedTextField();
        comboUFElaborador = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ComboFormacaoElaborador1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Data de Nascimento");

        textDataNascElaborador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        jLabel4.setText("Telefone");

        jLabel5.setText("Celular");

        jLabel3.setText("RG");

        jLabel1.setText("Nome");

        textNomeElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeElaboradorActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        buttonCancelarElaborador.setText("Cancelar");
        buttonCancelarElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarElaboradorActionPerformed(evt);
            }
        });

        buttonAtualizarElaborador.setText("Altualizar");
        buttonAtualizarElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarElaboradorActionPerformed(evt);
            }
        });

        textBairroElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBairroElaboradorActionPerformed(evt);
            }
        });

        jLabel14.setText("Formação");

        textCEPElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCEPElaboradorActionPerformed(evt);
            }
        });

        textRGElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRGElaboradorActionPerformed(evt);
            }
        });

        jLabel8.setText("Cidade");

        jLabel7.setText("UF");

        comboUFElaborador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RR", "RS", "RO", "SC", "SE", "SP", "TO", " ", " " }));

        jLabel13.setText("Complemento");

        jLabel10.setText("Cep");

        jLabel9.setText("Bairro");

        jLabel11.setText("Logradouro");

        jLabel12.setText("Numero");

        ComboFormacaoElaborador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Graduado", "Mestrado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textNomeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(textDataNascElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(ComboFormacaoElaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(comboUFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(textLogradouroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(textCidadeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addGap(36, 36, 36)
                        .addComponent(textNumeroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23)
                        .addComponent(textBairroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(textComplementoElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)
                        .addComponent(textCEPElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(buttonCancelarElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buttonAtualizarElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(textRGElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(textCelularElaborador))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(textCPFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)
                                .addComponent(textTelefoneElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(textNomeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCPFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefoneElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(textRGElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textCelularElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textDataNascElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(ComboFormacaoElaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboUFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLogradouroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCidadeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNumeroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(textBairroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textComplementoElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(textCEPElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancelarElaborador)
                    .addComponent(buttonAtualizarElaborador))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void textNomeElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeElaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeElaboradorActionPerformed

    private void buttonAtualizarElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarElaboradorActionPerformed
        // TODO add your handling code here:
        
          try {
              Elaborador elaborador= new Elaborador();
              elaborador.setId(cod);
              elaborador.setNome(textNomeElaborador.getText());
              elaborador.setCpf(textCPFElaborador.getText());
              elaborador.setRg(textRGElaborador.getText());
              elaborador.setFormacao(ComboFormacaoElaborador1.getSelectedItem().toString());
              elaborador.setTelefone(textTelefoneElaborador.getText());
              elaborador.setCelular(textCelularElaborador.getText());
              Endereco endereco = new Endereco();
        endereco.setCep(textCEPElaborador.getText());
        endereco.setBairro(textBairroElaborador.getText());
        endereco.setCidade(textCidadeElaborador.getText());
        endereco.setComplemento(textComplementoElaborador.getText());
        endereco.setNumero(textNumeroElaborador.getText());
        endereco.setUf(comboUFElaborador.getSelectedItem().toString());
        endereco.setLogradouro(textLogradouroElaborador.getText());
        elaborador.setEndereco(endereco);
        Calendar c = Calendar.getInstance();
        DateFormat f = DateFormat.getDateInstance();
        Date d = f.parse(textDataNascElaborador.getText());
        c.setTime(d);
        elaborador.setData_nasc(c);
              fachada.atualizarElaborador(elaborador);
              JOptionPane.showMessageDialog(rootPane,"Elaborador atualizado com sucesso");
              le.carregarTabelaElaborador();
              this.dispose();
          } catch (Exception ex) {
          JOptionPane.showMessageDialog(rootPane, ex.getMessage());
          }
      
       
        
    }//GEN-LAST:event_buttonAtualizarElaboradorActionPerformed

    private void textCEPElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCEPElaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCEPElaboradorActionPerformed

    private void textRGElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRGElaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRGElaboradorActionPerformed

    private void textBairroElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBairroElaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBairroElaboradorActionPerformed

    private void buttonCancelarElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarElaboradorActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonCancelarElaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarElaborador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboFormacaoElaborador1;
    private javax.swing.JButton buttonAtualizarElaborador;
    private javax.swing.JButton buttonCancelarElaborador;
    private javax.swing.JComboBox comboUFElaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textBairroElaborador;
    private javax.swing.JFormattedTextField textCEPElaborador;
    private javax.swing.JFormattedTextField textCPFElaborador;
    private javax.swing.JFormattedTextField textCelularElaborador;
    private javax.swing.JTextField textCidadeElaborador;
    private javax.swing.JTextField textComplementoElaborador;
    private javax.swing.JFormattedTextField textDataNascElaborador;
    private javax.swing.JTextField textLogradouroElaborador;
    private javax.swing.JTextField textNomeElaborador;
    private javax.swing.JTextField textNumeroElaborador;
    private javax.swing.JFormattedTextField textRGElaborador;
    private javax.swing.JFormattedTextField textTelefoneElaborador;
    // End of variables declaration//GEN-END:variables
}
