/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Elaborador;
import classes.Endereco;
import fachada.Fachada;
import fachada.IFachada;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author RAFAELSANTIAGO
 */
public class CRUDElaborador extends javax.swing.JFrame {

    IFachada fachada = Fachada.obterInstancia();
    ListarElaborador le;
    /**
     * Creates new form CRUDElaborador
     */
    public CRUDElaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLimparElaborador = new javax.swing.JButton();
        buttonSalvarElaborador = new javax.swing.JButton();
        textComplementoElaborador = new javax.swing.JTextField();
        textNomeElaborador = new javax.swing.JTextField();
        textDataNascElaborador = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textTelefoneElaborador = new javax.swing.JFormattedTextField();
        textCPFElaborador = new javax.swing.JFormattedTextField();
        textRGElaborador = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textCelularElaborador = new javax.swing.JFormattedTextField();
        comboUFElaborador = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textBairroElaborador = new javax.swing.JTextField();
        textLogradouroElaborador = new javax.swing.JTextField();
        textNumeroElaborador = new javax.swing.JTextField();
        textCEPElaborador = new javax.swing.JFormattedTextField();
        textCidadeElaborador = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ComboFormacaoElaborador = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonLimparElaborador.setText("Limpar");
        buttonLimparElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparElaboradorActionPerformed(evt);
            }
        });

        buttonSalvarElaborador.setText("Salvar");
        buttonSalvarElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarElaboradorActionPerformed(evt);
            }
        });

        textComplementoElaborador.setText("B");

        textNomeElaborador.setText("Antônio Fábio");
        textNomeElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeElaboradorActionPerformed(evt);
            }
        });

        textDataNascElaborador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        textDataNascElaborador.setText("20/12/1991");

        jLabel5.setText("Celular");

        jLabel6.setText("Data de Nascimento");

        textTelefoneElaborador.setText("(81)3031-3534");

        textCPFElaborador.setText("089.947.684-83");

        textRGElaborador.setText("7.699.732");

        jLabel8.setText("Cidade");

        jLabel7.setText("UF");

        textCelularElaborador.setText("(81)9999-9999");

        comboUFElaborador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RR", "RS", "RO", "SC", "SE", "SP", "TO", " ", " " }));

        jLabel13.setText("Complemento");

        jLabel10.setText("Cep");

        jLabel9.setText("Bairro");

        jLabel12.setText("Numero");

        jLabel11.setText("Logradouro");

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel4.setText("Telefone");

        jLabel3.setText("RG");

        textBairroElaborador.setText("Campo Grande");

        textLogradouroElaborador.setText("Rua Dr. Machado");

        textNumeroElaborador.setText("645");

        textCEPElaborador.setText("12345-123");
        textCEPElaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCEPElaboradorActionPerformed(evt);
            }
        });

        textCidadeElaborador.setText("Recife");

        jLabel14.setText("Formação");

        ComboFormacaoElaborador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Graduado", "Mestrado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textNomeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(textCPFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addComponent(textTelefoneElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(textRGElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(textCelularElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(textDataNascElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(ComboFormacaoElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(comboUFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(textLogradouroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(textCidadeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addGap(36, 36, 36)
                        .addComponent(textNumeroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23)
                        .addComponent(textBairroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(textComplementoElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)
                        .addComponent(textCEPElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(buttonLimparElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buttonSalvarElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(textNomeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCPFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefoneElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(textRGElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textCelularElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboFormacaoElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(textDataNascElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboUFElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLogradouroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCidadeElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNumeroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(textBairroElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(textComplementoElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(textCEPElaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLimparElaborador)
                    .addComponent(buttonSalvarElaborador))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarElaboradorActionPerformed
        // TODO add your handling code here:

        try {
            Elaborador elaborador = new Elaborador();

            elaborador.setNome(textNomeElaborador.getText());
            elaborador.setCpf(textCPFElaborador.getText());
            elaborador.setRg(textRGElaborador.getText());
            elaborador.setTelefone(textTelefoneElaborador.getText());
            elaborador.setCelular(textCelularElaborador.getText());
            elaborador.setFormacao(ComboFormacaoElaborador.getSelectedItem().toString());
            //elaborador.setSalario(Double.parseDouble(textSalarioFuncionario.getText()));
            //elaborador.setCtps(textCTPSFuncionario.getText());
            Endereco endereco = new Endereco();
            endereco.setCep(textCEPElaborador.getText());
            endereco.setBairro(textBairroElaborador.getText());
            endereco.setCidade(textCidadeElaborador.getText());
            endereco.setComplemento(textComplementoElaborador.getText());
            endereco.setNumero(textNumeroElaborador.getText());
            endereco.setUf(comboUFElaborador.getSelectedItem().toString());
            endereco.setLogradouro(textLogradouroElaborador.getText());
            elaborador.setEndereco(endereco);
            Calendar c = Calendar.getInstance();
            DateFormat f = DateFormat.getDateInstance();
            Date d = f.parse(textDataNascElaborador.getText());
            c.setTime(d);
            elaborador.setData_nasc(c);
            fachada.inserirElaborador(elaborador);
            JOptionPane.showMessageDialog(rootPane, "Elaborador cadastrado com sucesso");
             //le.
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_buttonSalvarElaboradorActionPerformed

    private void textNomeElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeElaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeElaboradorActionPerformed

    private void textCEPElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCEPElaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCEPElaboradorActionPerformed

    private void buttonLimparElaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparElaboradorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonLimparElaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDElaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDElaborador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboFormacaoElaborador;
    private javax.swing.JButton buttonLimparElaborador;
    private javax.swing.JButton buttonSalvarElaborador;
    private javax.swing.JComboBox comboUFElaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textBairroElaborador;
    private javax.swing.JFormattedTextField textCEPElaborador;
    private javax.swing.JFormattedTextField textCPFElaborador;
    private javax.swing.JFormattedTextField textCelularElaborador;
    private javax.swing.JTextField textCidadeElaborador;
    private javax.swing.JTextField textComplementoElaborador;
    private javax.swing.JFormattedTextField textDataNascElaborador;
    private javax.swing.JTextField textLogradouroElaborador;
    private javax.swing.JTextField textNomeElaborador;
    private javax.swing.JTextField textNumeroElaborador;
    private javax.swing.JFormattedTextField textRGElaborador;
    private javax.swing.JFormattedTextField textTelefoneElaborador;
    // End of variables declaration//GEN-END:variables
}
