/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.AreaConcurso;
import classes.DiaFase;
import classes.Elaborador;
import classes.Fase;
import fachada.Fachada;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELSANTIAGO
 */
public class CRUDFase extends javax.swing.JFrame {

    /**
     * Creates new form CRUDFase
     */
    Fase fase = new Fase();
    DefaultTableModel modelo = new DefaultTableModel();
    Fachada fachada = Fachada.obterInstancia();
    CRUDAreaConcurso crudac;
   ArrayList<DiaFase> dias_fase = new ArrayList<DiaFase>();

    public CRUDFase(CRUDAreaConcurso crudac) {
        try {
            initComponents();
            this.crudac = crudac;
            ArrayList<DiaFase> dias_fase;
              DiaFase diaFase = new DiaFase();
            Date data = new Date("12/11/2012");
            diaFase.getDataDia().setTime(data);
            SimpleDateFormat df = new SimpleDateFormat("HH:mm");
            diaFase.getHoraInicial().setTime(df.parse("12:00"));
            diaFase.getHoraFinal().setTime(df.parse("14:30"));
//            DiaFase diaFase2 = new DiaFase();
//            Date data2 = new Date("12/12/2012");
//            diaFase2.getDataDia().setTime(data2);
//            diaFase2.getHoraInicial().setTime(df.parse("13:00"));
//            diaFase2.getHoraFinal().setTime(df.parse("17:30"));
//            fase.getDiaFase().add(diaFase);
//            fase.getDiaFase().add(diaFase2);
            this.atualizarListaDiaFase();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private CRUDFase() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void atualizarListaDiaFase() {
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Data", "Hora Inicial", "Hora Final"});
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdf2 = new SimpleDateFormat("HH:mm");
        for (DiaFase diaFase : fase.getDiasFase()) {
            modelo.addRow(new Object[]{sdf.format(diaFase.getDataDia().getTime()).toString(), sdf2.format(diaFase.getHoraInicial().getTime()).toString(), sdf2.format(diaFase.getHoraFinal().getTime()).toString()});
        }
        TableListarDiaFase.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonLimparFase = new javax.swing.JButton();
        ButtonSalvarFase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListarDiaFase = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonLimparFase.setText("Limpar");

        ButtonSalvarFase.setText("Salvar");
        ButtonSalvarFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarFaseActionPerformed(evt);
            }
        });

        TableListarDiaFase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableListarDiaFase.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(TableListarDiaFase);

        jButton1.setText("Cadastrar Dia da Fase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover dia da Fase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Alterar Dia da Fase");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addContainerGap(25, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonLimparFase)
                                .addGap(27, 27, 27)
                                .addComponent(ButtonSalvarFase)
                                .addGap(144, 144, 144))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLimparFase)
                    .addComponent(ButtonSalvarFase))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CRUDDiaFase cruddf = new CRUDDiaFase(this);
        cruddf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonSalvarFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarFaseActionPerformed
        try {
            
            
            
            // TODO add your handling code here:
            for (DiaFase df : fase.getDiasFase()) {
                df.setFase(fase);
            }
            crudac.fases.add(fase);
            crudac.carregarListaFases();
            this.dispose();
            JOptionPane.showMessageDialog(this, "Fase Cadastrada com sucesso");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_ButtonSalvarFaseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

      try{
      if(TableListarDiaFase.getSelectedRow()!=-1){
          fase.getDiasFase().remove(TableListarDiaFase.getSelectedRow());
          atualizarListaDiaFase();
      JOptionPane.showMessageDialog(rootPane, "Dia Fase removido com sucesso");
      } else{
      JOptionPane.showMessageDialog(rootPane,"Selecione Dia Fase para remover");
      }
      
       
    

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());}
    //    }
//        DiaFase diaFase = new DiaFase();
//        if (TableListarDiaFase.getSelectedRow() >= 0){  
//            modelo.removeRow(TableListarDiaFase.getSelectedRow());  
//           TableListarDiaFase.setModel(modelo);
//            this.fase.getDiaFase().remove(diaFase);
//            this.atualizarListaDiaFase();
//            //fase.setDiaFase(null);
//            
//        }else{  
//            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");  
//        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      if(TableListarDiaFase.getSelectedRow()==-1){
      JOptionPane.showMessageDialog(rootPane,"Selecione Dia Fase para alterar");
      }else{
        int codigo= TableListarDiaFase.getSelectedRow();
        AlterarDiaFase altDiaFase= new AlterarDiaFase(this, codigo);
        altDiaFase.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDFase().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLimparFase;
    private javax.swing.JButton ButtonSalvarFase;
    private javax.swing.JTable TableListarDiaFase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
