/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.CartaoResposta;
import classes.Concursando;
import classes.DiaFase;
import classes.Fase;
import classes.Prova;
import fachada.Fachada;
import fachada.IFachada;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antônio
 */
public class ListarConcursandosFase extends javax.swing.JFrame {

    /**
     * Creates new form ListarConcursandosFase
     */
    Fase fase;
    List<Prova> provas = new ArrayList<Prova>();
    IFachada fachada = Fachada.obterInstancia();

    public ListarConcursandosFase(Fase fase) {
        initComponents();
        try {
            fase = fachada.consultarFasePorId(fase.getId());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        this.fase = fase;
        for (DiaFase diaFase : fase.getDiasFase()) {
            for (Prova prova : diaFase.getProvas()) {
                provas.add(prova);
            }
        }
        this.carregarListaConcursandos();
        this.carregarListaProvasFase();
    }

    private ListarConcursandosFase() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void carregarListaConcursandos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Nome", "CPF"});
        for (Concursando concursando : fase.getAreaconcurso().getConcursando()) {
            modelo.addRow(new Object[]{concursando.getNome(), concursando.getCpf()});
        }
        TableConcursandosFase.setModel(modelo);
    }

    public void carregarListaProvasFase() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Área de Conhecimento", "Data da Prova"});
        for (Prova prova : provas) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            modelo.addRow(new Object[]{prova.getGenero().getGenero(), sdf.format(prova.getDiaFase().getDataDia().getTime())});
        }
        TableProvasFase.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableConcursandosFase = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProvasFase = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        label1.setText("label1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        TableConcursandosFase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableConcursandosFase);

        TableProvasFase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableProvasFase);

        jButton2.setText("Cadastrar Cartao Resposta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (TableConcursandosFase.getSelectedRow() != -1) {
            if (TableProvasFase.getSelectedRow() != -1) {
                try {
                    List<CartaoResposta> cartoesResposta = fachada.consultarCartoesRespostaConcursandoProva(provas.get(TableProvasFase.getSelectedRow()), fase.getAreaconcurso().getConcursando().get(TableConcursandosFase.getSelectedRow()));
                    if (cartoesResposta.size() > 0) {
                        if (JOptionPane.showConfirmDialog(rootPane, "Este concursando já possui um cartão resposta cadastrado para esta prova. \n Gostaria de altera-lo? ", "Alterar Cartao Resposta", JOptionPane.YES_NO_OPTION) == 0) {
                            AlterarGabaritoProva agp = new AlterarGabaritoProva(provas.get(TableConcursandosFase.getSelectedRow()), cartoesResposta.get(0));
                            agp.setVisible(true);
                        }
                    } else {
                        CRUDGabaritoProva crudrp = new CRUDGabaritoProva(fase.getAreaconcurso().getConcursando().get(TableConcursandosFase.getSelectedRow()), provas.get(TableProvasFase.getSelectedRow()));
                        crudrp.setVisible(true);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarConcursandosFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarConcursandosFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarConcursandosFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarConcursandosFase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarConcursandosFase().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableConcursandosFase;
    private javax.swing.JTable TableProvasFase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
