/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Questao;
import classes.QuestaoDiscursiva;
import classes.QuestaoMultiplaEscolha;
import fachada.Fachada;
import fachada.IFachada;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

    /**
 *
 * @author RAFAELSANTIAGO
 */
public class ListarQuestao extends javax.swing.JFrame {

    /**
     * Creates new form ListarQuestao
     */
    ArrayList<QuestaoMultiplaEscolha> questoesMultiplaEscolha;
    ArrayList<QuestaoDiscursiva> questoesDiscursiva;
    IFachada fachada = Fachada.obterInstancia();

    public ListarQuestao() {
        try {
            initComponents();
            this.carregarListaQuestoesDiscursiva();
            this.carregarListaQuestoesMultiplaEscolha();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    public void carregarListaQuestoesDiscursiva() {
        try {
            questoesDiscursiva = (ArrayList<QuestaoDiscursiva>) fachada.consultarTodosQuestaoDiscursiva();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Questão", "Referência", "Gênero"});
            for (QuestaoDiscursiva questDisc : questoesDiscursiva) {
                modelo.addRow(new Object[]{questDisc.getTexto(), questDisc.getReferencia(), questDisc.getGenero().getGenero()});
            }
            TableListarQuestaoDiscursiva.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    public void carregarListaQuestoesMultiplaEscolha() {
        try {
            questoesMultiplaEscolha = (ArrayList<QuestaoMultiplaEscolha>) fachada.consultarTodosQuestaoMultiplaEscolha();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Questão", "Referência", "Gênero"});
            for (QuestaoMultiplaEscolha questMult : questoesMultiplaEscolha) {
                modelo.addRow(new Object[]{questMult.getTexto(), questMult.getReferencia(), questMult.getGenero().getGenero()});
            }
            TableListarQuestaoMultipla.setModel(modelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListarQuestaoDiscursiva = new javax.swing.JTable();
        ButtonRemoverQuestaoDiscursiva = new javax.swing.JButton();
        ButtonAlterarQuestaoDiscursiva = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableListarQuestaoMultipla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ButtonAlterarQuestaoMultiplaEscolha = new javax.swing.JButton();
        ButtonRemoverQuestaoMultiplaEscolha = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Lista de Questoes Discursivas");

        TableListarQuestaoDiscursiva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableListarQuestaoDiscursiva);

        ButtonRemoverQuestaoDiscursiva.setText("Remover Questões Disc");
        ButtonRemoverQuestaoDiscursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoverQuestaoDiscursivaActionPerformed(evt);
            }
        });

        ButtonAlterarQuestaoDiscursiva.setText("Alterar Questões Disc");
        ButtonAlterarQuestaoDiscursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarQuestaoDiscursivaActionPerformed(evt);
            }
        });

        TableListarQuestaoMultipla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableListarQuestaoMultipla);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Lista de Questoes Multipla Escolha");

        ButtonAlterarQuestaoMultiplaEscolha.setText("Alterar Questões Mult");
        ButtonAlterarQuestaoMultiplaEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarQuestaoMultiplaEscolhaActionPerformed(evt);
            }
        });

        ButtonRemoverQuestaoMultiplaEscolha.setText("Remover Questões Mult");
        ButtonRemoverQuestaoMultiplaEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoverQuestaoMultiplaEscolhaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Cadastrar Questão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonRemoverQuestaoMultiplaEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonAlterarQuestaoMultiplaEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonRemoverQuestaoDiscursiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonAlterarQuestaoDiscursiva, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRemoverQuestaoMultiplaEscolha)
                    .addComponent(ButtonAlterarQuestaoMultiplaEscolha)
                    .addComponent(ButtonRemoverQuestaoDiscursiva)
                    .addComponent(ButtonAlterarQuestaoDiscursiva))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CRUDQuestao crudq = new CRUDQuestao(this);
        crudq.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonRemoverQuestaoMultiplaEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoverQuestaoMultiplaEscolhaActionPerformed
        // TODO add your handling code here:
       if(TableListarQuestaoMultipla.getSelectedRow()==-1){
       JOptionPane.showMessageDialog(rootPane, "Selecione uma Questão Multipla escolha para remover");
       }else{
        RemoverQuestaoMultiplaEscolha questaoMultiplaEscolha = new RemoverQuestaoMultiplaEscolha(this, questoesMultiplaEscolha.get(TableListarQuestaoMultipla.getSelectedRow()));
        questaoMultiplaEscolha.setVisible(true);
    }//GEN-LAST:event_ButtonRemoverQuestaoMultiplaEscolhaActionPerformed
    }
    private void ButtonRemoverQuestaoDiscursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoverQuestaoDiscursivaActionPerformed
        // TODO add your handling code here:
        if(TableListarQuestaoDiscursiva.getSelectedRow()==-1){
       JOptionPane.showMessageDialog(rootPane, "Selecione uma Questão Discursiva escolha para remover");
       }else{
        RemoverQuestaoDiscursiva questaoDiscursiva = new RemoverQuestaoDiscursiva(this, questoesDiscursiva.get(TableListarQuestaoDiscursiva.getSelectedRow()));
        questaoDiscursiva.setVisible(true);
    }//GEN-LAST:event_ButtonRemoverQuestaoDiscursivaActionPerformed
    }
    private void ButtonAlterarQuestaoMultiplaEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarQuestaoMultiplaEscolhaActionPerformed
        // TODO add your handling code here:
       if(TableListarQuestaoMultipla.getSelectedRow()==-1){
       JOptionPane.showMessageDialog(rootPane, "Selecione uma Questão Multipla escolha para Alterar");
       }else{
        AlterarQuestaoMultiplaEscolha altqM= new AlterarQuestaoMultiplaEscolha(this, questoesMultiplaEscolha.get(TableListarQuestaoMultipla.getSelectedRow()));
        altqM.setVisible(true);
    }//GEN-LAST:event_ButtonAlterarQuestaoMultiplaEscolhaActionPerformed
    }
    private void ButtonAlterarQuestaoDiscursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarQuestaoDiscursivaActionPerformed
        // TODO add your handling code here:
        if(TableListarQuestaoDiscursiva.getSelectedRow()==-1){
       JOptionPane.showMessageDialog(rootPane, "Selecione uma Questão Discursiva escolha para Alterar");
       }else{
        AlterarQuestaoDiscursiva altqD= new AlterarQuestaoDiscursiva(this, questoesDiscursiva.get(TableListarQuestaoDiscursiva.getSelectedRow()));
        altqD.setVisible(true);
    }//GEN-LAST:event_ButtonAlterarQuestaoDiscursivaActionPerformed

//    void setVisible(boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarQuestao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlterarQuestaoDiscursiva;
    private javax.swing.JButton ButtonAlterarQuestaoMultiplaEscolha;
    private javax.swing.JButton ButtonRemoverQuestaoDiscursiva;
    private javax.swing.JButton ButtonRemoverQuestaoMultiplaEscolha;
    private javax.swing.JTable TableListarQuestaoDiscursiva;
    private javax.swing.JTable TableListarQuestaoMultipla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
