/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Empresa;
import classes.Gabarito;
import classes.Prova;
import fachada.Fachada;
import fachada.IFachada;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELSANTIAGO
 */
public class ListarProva extends javax.swing.JFrame {

    IFachada fachada = Fachada.obterInstancia();
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Prova> provas = new ArrayList<Prova>();

    /**
     * Creates new form ListarProva
     */
    public ListarProva() {
        initComponents();
    }

    public void carregarTabelaProva() {
        try {
            modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Id", "Genero", "AreaConcurso", "Concurso", "Fase", "DiaFase"});
            provas = new ArrayList<Prova>();
            provas = (ArrayList<Prova>) fachada.consultarTodosProva();
            String fase;
            String dataFase;
            for (Prova prova : provas) {
                modelo.addRow(new String[]{Long.toString(prova.getId()), prova.getGenero().getGenero(), prova.getDiaFase().getFase().getAreaconcurso().getNome(), prova.getDiaFase().getFase().getAreaconcurso().getConcurso().getNomeConcurso(), fase = Long.toString(prova.getDiaFase().getFase().getId()), (prova.getDiaFase().getDataDia().get(5) + "/" + prova.getDiaFase().getDataDia().get(2) + "/" + prova.getDiaFase().getDataDia().get(1))});
            }
            TableListarProva.setModel(modelo);
            // TODO add your handling code here:
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonAlterarProva = new javax.swing.JButton();
        ButtonRemoverProva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListarProva = new javax.swing.JTable();
        ButtonCadastrarProva = new javax.swing.JButton();
        ButtonListarProva = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Lista de Provas");

        ButtonAlterarProva.setText("Alterar");

        ButtonRemoverProva.setText("Remover");
        ButtonRemoverProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoverProvaActionPerformed(evt);
            }
        });

        TableListarProva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableListarProva);

        ButtonCadastrarProva.setText("Cadastrar");
        ButtonCadastrarProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarProvaActionPerformed(evt);
            }
        });

        ButtonListarProva.setText("Listar");
        ButtonListarProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarProvaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Gabarito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ButtonListarProva, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCadastrarProva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonRemoverProva, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAlterarProva, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRemoverProva)
                    .addComponent(ButtonAlterarProva)
                    .addComponent(ButtonCadastrarProva)
                    .addComponent(ButtonListarProva)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCadastrarProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarProvaActionPerformed
        // TODO add your handling code here:
        CRUDProva crdP = new CRUDProva();
        crdP.setVisible(true);

    }//GEN-LAST:event_ButtonCadastrarProvaActionPerformed

    private void ButtonListarProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarProvaActionPerformed
        // TODO add your handling code here:
        this.carregarTabelaProva();
    }//GEN-LAST:event_ButtonListarProvaActionPerformed

    private void ButtonRemoverProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoverProvaActionPerformed
        // TODO add your handling code here:
        Prova prova = new Prova();
        try {
            int codigo = TableListarProva.getSelectedRow();
            prova = fachada.consultarProvaPorId(Long.parseLong(TableListarProva.getValueAt(codigo, 0).toString()));
            RemoverProva rmvP = new RemoverProva(prova, this);
            rmvP.setVisible(true);
            this.carregarTabelaProva();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_ButtonRemoverProvaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (TableListarProva.getSelectedRow() != -1) {
                List<Gabarito> gabaritos = fachada.consultarGabaritoProva(provas.get(TableListarProva.getSelectedRow()).getId());
                if (gabaritos.size() > 0) {
                    if (JOptionPane.showConfirmDialog(rootPane, "Esta prova já possui um gabarito. \n Gostaria de altera-lo? ", "Alterar Gabarito", JOptionPane.YES_NO_OPTION) == 0) {
                        AlterarGabaritoProva agp = new AlterarGabaritoProva(provas.get(TableListarProva.getSelectedRow()), gabaritos.get(0));
                        agp.setVisible(true);
                    }
                } else {
                    CRUDGabaritoProva cgp = new CRUDGabaritoProva(provas.get(TableListarProva.getSelectedRow()));
                    cgp.setVisible(true);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProva().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlterarProva;
    private javax.swing.JButton ButtonCadastrarProva;
    private javax.swing.JButton ButtonListarProva;
    private javax.swing.JButton ButtonRemoverProva;
    private javax.swing.JTable TableListarProva;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
